Handle suspend_process_group for Windows platform
SIGTSTP isn't handled on Windows, so we need to handle it manually otherwise it wouldn't compile : 

```
error[E0425]: cannot find value `SIGTSTP` in crate `libc`
   --> src\api.rs:853:36
    |
853 |         signal_process_group(libc::SIGTSTP)
    |                                    ^^^^^^^ not found in `libc`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `paintcannon` (lib) due to 1 previous error
```